#ifndef CONSTANTS_HH__
#define CONSTANTS_HH__

/*
 *  COLOR.HPP
 */

#define COLOR_COMPONENT_OVERFLOW_CHECK
#define COLOR_IMPLICIT_ALPHA_ASSIGNMENT
// #define COLOR_INCLUDE_ALPHA_IN_COMPARISON
// #define COLOR_NO_C_STYLE_CONSTRUCTION

#endif /* !CONSTANTS_HH__ */